# CI.yaml --- Check OpenVox module

name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: '17 2 * * 0'

jobs:
  qa:
    name: OpenVox ${{ matrix.puppet_version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        openvox_version: [8]

    container:
      image: ghcr.io/voxpupuli/voxbox:${{ matrix.openvox_version }}
      volumes:
        - ${{ github.workspace }}:/repo:Z

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Check
        run: rake -f /Rakefile check

      - name: Lint
        run: rake -f /Rakefile lint

      - name: YAML Lint
        run: yamllint data/

      - name: Metadata Lint
        run: rake -f /Rakefile metadata_lint

      - name: Rubocop
        run: rake -f /Rakefile rubocop

      - name: Syntax
        run: rake -f /Rakefile syntax

      - name: Unit Tests
        run: rake -f /Rakefile spec
